### ISSUE TITLE
Color, Font Size, and CSS Related Customization Option 

### ISSUE THREAD

**Issue by Mobashir1995** [timqian/chart.xkcd#11]
There is no option to change **_Color_**, **_Font Size_**, **_Font Family_**, and other **_CSS_** Related Styles.

**_Chart JS_** and other Similar Plugin has those Options.

Can you add those options on this plugin?

**Comment by timqian** [comment]
Yeah, options to config chart is on my plan, should be finished in 1-2 weeks

**Comment by peterbe** [comment]
<img width="808" alt="Screen Shot 2019-08-29 at 2 00 16 PM" src="https://user-images.githubusercontent.com/26739/63964955-31a6ca00-ca66-11e9-8437-4de8dfd336e9.png">

I clearly need to figure out how to control the colors. 
What's curious is that I don't specify *any* colors yet the axis becomes white.

**Comment by timqian** [comment]
@peterbe I use d3-axis to draw the axis, it automatically changes color when background color changes I think. I will try to find time in the weekend to add options to update color and font.

What I can think of for now is the following options, suggestions?

```
dataColors,
axisColor,
fontColor,
fontFamily,
titleSize,
labelSize,
```

**Comment by peterbe** [comment]
I would love a default color too. Then, for example, `fontColor` would be `var fontColor = options.fontColor || options.defaulltColor || 'black'`

**Comment by timqian** [comment]
`dataColors` and `fontFamily` options are added in [v1.1](https://github.com/timqian/chart.xkcd/releases/tag/v1.1)

<img width="404" alt="Screen Shot 2019-09-03 at 2 56 53 PM" src="https://user-images.githubusercontent.com/5512552/64150578-1c151400-ce5b-11e9-990f-01ec9462dc60.png">

While implementing axis and fontColors I think it might be better to implement a `dark mode` for chart.xkcd to make it easier to use. 

Further discussions about dark mode - https://github.com/timqian/chart.xkcd/issues/21
