### ISSUE TITLE
More legend placements: bottom left/right or move out of the graph part

### ISSUE THREAD

**Issue by ChildishGiant** [timqian/chart.xkcd#17]
It'd be nice to have options for the legend to be in the bottom left/right. This'd be a bodge fix for text overlapping the titles too.

**Comment by timqian** [comment]
Also, when there are more than 4 labels, the legend is taking too much space in mobile device
<img width="238" alt="Screen Shot 2019-08-27 at 9 36 23 AM" src="https://user-images.githubusercontent.com/5512552/63734277-2dd04780-c8ae-11e9-87fd-d16198c9e35f.png">

Besides enabling `bottom left/right` options, I plan to make it possible to move the legend out of the graph. This feature is planned to be shipped in v1.2

**Comment by timqian** [comment]
enabled in v1.1.5
