### ISSUE TITLE
Does chart.xkcd Have A Privacy Policy?

### ISSUE THREAD

**Issue by dm-p** [timqian/chart.xkcd#18]
I've observed that the library doesn't collect/send any data but wondered if it might be useful to add a privacy policy confirming this for sure in the documentation/readme?

**Comment by timqian** [comment]
This is a pure frontend lib and does not collect/send any data.

But I am not familiar with Privacy Policy, do you have any example repo with similar `privacy policy` documentation?

**Comment by dm-p** [comment]
I'm developing a wrapper for chart.xkcd for Power BI and it's nearly ready, so I'm just working on the documentation and thought I'd better add one so juct wante to confirm my thinking - I had reviewed the code and was happy that it didn't collect anything. 

As an exmaple, I'll provide you with one of mine - [here's a custom visual I already have in production for Power BI](https://bitbucket.org/dm-p/power-bi-visuals-violin-plot/wiki/Privacy%20Policy). Privacy policies can potentially much more complicated than this if they do collect data, but this one is what most people would be keen to be assured of when using a product.

As Power BI visuals are written in TypeScript and there's potential for other server-side stuff to be added in there, users generally like some assurance in terms of a privacy policy. While the code is open source, most people using Power BI are not familiar with JS/TS and will not have the capability to vet this themselves, so it is a common question asked of custom visual developers.

I'll be providing this confirmation from my side for the solution and your above comment from yourself is all I need to confirm the visual - as a full solution - doesn't do anything other that use data for display purposes. 

Thanks so much for responding, and thanks so much for a great library! I'll be sure to send you the repo when it's ready, or add it to #14, if that's okay?

**Comment by timqian** [comment]
@dm-p That's ok, thanks
