### ISSUE TITLE
[new chart type]: radar chart

### ISSUE THREAD

**Issue by devnewton** [timqian/chart.xkcd#2]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/timqian/chart.xkcd/issues/2)

A useful chart type: https://www.chartjs.org/samples/latest/charts/area/radar.html

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)
### Submitted pull Requests
- [#25 Radar chart (new chart type)](https://issuehunt.io/r/timqian/chart.xkcd/pull/25)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/timqian/chart.xkcd/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by timqian** [comment]
Thanks to @denisinvader , the radar chart is introduced in v1.1.3 
https://timqian.com/chart.xkcd/#radar_chart
