### ISSUE TITLE
Impossible to specify ticks that are different from xaxis data labels

### ISSUE THREAD

**Issue by mseri** [timqian/chart.xkcd#5]
Often I have many more points on the x axis than what I would want to show on the plot. It is currently impossible to specify a set of xticks different from the whole set of x data.

**Comment by unhammer** [comment]
Scatter plots would be nice :-)

**Comment by timqian** [comment]
@mseri try the [XY chart](https://timqian.com/chart.xkcd/#xy_chart) introduced in `v1.0.7`, it supports
- scatter plots
- tick number customization

**Comment by mseri** [comment]
Works perfectly, thanks!
