### ISSUE TITLE
the label border is incorrect with Chinese

### ISSUE THREAD

**Issue by SimuraEpona** [timqian/chart.xkcd#51]
**Describe the bug**

the label is incorrect in Chinese

**Screenshot**

<img width="275" alt="image" src="https://user-images.githubusercontent.com/13564077/68536957-9fd90880-0396-11ea-8aa5-d60dbe8bd541.png">

**How to reproduce**

[https://codepen.io/simuraepona/pen/xxxzNJz](https://codepen.io/simuraepona/pen/xxxzNJz)

**Comment by timqian** [comment]
@SimuraEpona Thanks for reporting this bug, it is fixed via https://github.com/timqian/chart.xkcd/commit/52bf80e292a15f946eee1e665db44e3d1fddf99c

### Demo
https://codepen.io/timqian/pen/KKKBmXV
