### ISSUE TITLE
Is the docs complete?

### ISSUE THREAD

**Issue by obiwankenoobi** [timqian/chart.xkcd#8]
Hey man, great library! I wonder if the docs are completed and this is an example of a complete config?

```
 {
    title: 'Monthly income of an indie developer',
    xLabel: 'Month',
    yLabel: '$ Dollors',
    data: {
      labels:['1', '2', '3', '4', '5', '6','7', '8', '9', '10'],
      datasets: [{
        label: 'Plan',
        data: [30, 70, 200, 300, 500 ,800, 1500, 2900, 5000, 8000],
      }, {
        label: 'Reality',
        data: [0, 1, 30, 70, 80, 100, 50, 80, 40, 150],
      }]
    },
  }
```

**Comment by timqian** [comment]
@obiwankenoobi Yeah, for now these are all the possible configurations
`title`, `xLabel` and `yLabel` is optional

The doc is not complete, I will add it tomorrow.

Also, I am adding more configs and function to update the chart. Stay tuned

**Comment by obiwankenoobi** [comment]
@timqian cool! Anyway I dont know if you planned to create wrappers of the lib but I loved it  so I decided "react" it lol you can check this here https://github.com/obiwankenoobi/chart.xkcd-react Thanks for the awesome work!

**Comment by ChakshuGautam** [comment]
> @timqian cool! Anyway I dont know if you planned to create wrappers of the lib but I loved it so I decided "react" it lol you can check this here https://github.com/obiwankenoobi/chart.xkcd-react Thanks for the awesome work!

I will use if for sure.

**Comment by timqian** [comment]
@obiwankenoobi Awesome! Thanks for creating chart.xkcd-react, I don't have a plan to create similar wrappers. I will list it somewhere in the documentation.

One thing to notice is `chart.xkcd` is in its early stage, so more API will come and the current API might change. It will be great if you are willing to keep on maintaining `chart.xkcd-react`.

**Comment by obiwankenoobi** [comment]
@timqian for sure. I am watching the library and I will keep it updated with your api and docs. (:

**Comment by wistcc** [comment]
@timqian I saw the library and loved it. After seeing @obiwankenoobi react wrapper I decided to do the same but for Vue https://github.com/wistcc/chart.xkcd-vue-wrapper

I hope that this helps many people to use this awesome library.

Thanks for the great work!

**Comment by timqian** [comment]
@wistcc Thanks for creating the vue wrapper, I have listed it in the doc

In version 1.0.7 of chart.xkcd, I added more doc about the params. Closing this issue for now. Feel free to open it if you have further questions
